### PR TITLE
Fix figures

### PR DESCRIPTION
**Pull request by LinneaEriksson**
Added functions and tried to fix collisions, didn't work. Tried to add random shapes. Didn't work..

### CODE REVIEW

**Comment by LinneaEriksson** [comment]
Read above.

**Review by s0wie — COMMENTED** [review]
Looks good

**Review by s0wie — APPROVED** [review]
Looks good

**Comment by s0wie** [comment]
All bugs to figures seems to be fixed, they can move left, right, down and rotate. Looks good!

**Pull request merged**
